"""Automated engineering acceptance checker for MOC simulation results."""

from __future__ import annotations

from typing import Any, Mapping, TypedDict


class ViolationDetail(TypedDict):
    node_id: str
    check: str
    limit: float | bool
    actual: float | bool
    time_s: float | None
    message: str


class CheckResults(TypedDict):
    passed: bool
    is_si: bool
    violations: list[ViolationDetail]


def run_acceptance_checks(
    summary: Mapping[str, Any],
    *,
    max_pressure: float | dict[str, float] | None = None,
    min_pressure: float | dict[str, float] | None = None,
    allow_cavitation: bool = False,
    max_cavitation_duration_s: float = 0.0,
) -> CheckResults:
    """Run automated engineering acceptance checks on a StudySummary or StudySummarySI.

    Parameters
    ----------
    summary : dict
        A StudySummary or StudySummarySI dictionary generated by summarize_study() or summarize_study_si().
    max_pressure : float or dict[str, float], optional
        Maximum allowable pressure. Can be a single global threshold or a dict mapping node IDs to thresholds.
        Units are matching the summary (psi for US, kPa for SI).
    min_pressure : float or dict[str, float], optional
        Minimum allowable pressure. Can be a single global threshold or a dict mapping node IDs to thresholds.
        Units are matching the summary (psi for US, kPa for SI).
    allow_cavitation : bool, default False
        If False, any cavitation occurrence is considered a failure.
    max_cavitation_duration_s : float, default 0.0
        Maximum allowable cavitation duration in seconds. Only checked if allow_cavitation is True.

    Returns
    -------
    CheckResults
        A dictionary containing the overall passed status, whether SI units were detected, and a list of violations.
    """
    violations: list[ViolationDetail] = []
    passed = True

    # Auto-detect if summary is in SI units
    is_si = False
    nodes_summary = summary.get("nodes", {})
    if nodes_summary:
        first_node = next(iter(nodes_summary.values()))
        if "pressure_kpa" in first_node:
            is_si = True

    pressure_key = "pressure_kpa" if is_si else "pressure_psi"
    pressure_unit = "kPa" if is_si else "psi"

    for node_id, node_sum in nodes_summary.items():
        # Check maximum pressure limit
        if max_pressure is not None:
            limit = None
            if isinstance(max_pressure, dict):
                limit = max_pressure.get(node_id)
                if limit is None and "_default" in max_pressure:
                    limit = max_pressure["_default"]
            else:
                limit = max_pressure

            if limit is not None:
                actual_max = node_sum.get(pressure_key, {}).get("max")
                max_time = node_sum.get(pressure_key, {}).get("max_time_s")
                if actual_max is not None and actual_max > limit:
                    passed = False
                    violations.append(
                        ViolationDetail(
                            node_id=node_id,
                            check="max_pressure",
                            limit=limit,
                            actual=actual_max,
                            time_s=max_time,
                            message=(
                                f"Node '{node_id}' maximum pressure violation. "
                                f"Limit: {limit:.2f} {pressure_unit}, "
                                f"Actual: {actual_max:.2f} {pressure_unit} at {max_time:.2f} s"
                            ),
                        )
                    )

        # Check minimum pressure limit
        if min_pressure is not None:
            limit = None
            if isinstance(min_pressure, dict):
                limit = min_pressure.get(node_id)
                if limit is None and "_default" in min_pressure:
                    limit = min_pressure["_default"]
            else:
                limit = min_pressure

            if limit is not None:
                actual_min = node_sum.get(pressure_key, {}).get("min")
                min_time = node_sum.get(pressure_key, {}).get("min_time_s")
                if actual_min is not None and actual_min < limit:
                    passed = False
                    violations.append(
                        ViolationDetail(
                            node_id=node_id,
                            check="min_pressure",
                            limit=limit,
                            actual=actual_min,
                            time_s=min_time,
                            message=(
                                f"Node '{node_id}' subatmospheric minimum pressure violation. "
                                f"Limit: {limit:.2f} {pressure_unit}, "
                                f"Actual: {actual_min:.2f} {pressure_unit} at {min_time:.2f} s"
                            ),
                        )
                    )

        # Check cavitation duration limit
        cav_summary = node_sum.get("cavitation", {})
        cav_occurred = cav_summary.get("occurred", False)
        cav_duration = cav_summary.get("duration_s", 0.0)
        first_cav_time = cav_summary.get("first_time_s")

        if cav_occurred:
            if not allow_cavitation:
                passed = False
                violations.append(
                    ViolationDetail(
                        node_id=node_id,
                        check="cavitation",
                        limit=False,
                        actual=True,
                        time_s=first_cav_time,
                        message=(
                            f"Node '{node_id}' experienced cavitation (duration {cav_duration:.2f} s) "
                            f"starting at {first_cav_time:.2f} s"
                        ),
                    )
                )
            elif cav_duration > max_cavitation_duration_s:
                passed = False
                violations.append(
                    ViolationDetail(
                        node_id=node_id,
                        check="cavitation_duration",
                        limit=max_cavitation_duration_s,
                        actual=cav_duration,
                        time_s=first_cav_time,
                        message=(
                            f"Node '{node_id}' cavitation duration violation. "
                            f"Limit: {max_cavitation_duration_s:.2f} s, "
                            f"Actual: {cav_duration:.2f} s starting at {first_cav_time:.2f} s"
                        ),
                    )
                )

    return CheckResults(passed=passed, is_si=is_si, violations=violations)


def format_acceptance_report(check_results: CheckResults) -> str:
    """Format check results as a human-readable engineering report.

    Parameters
    ----------
    check_results : CheckResults
        The dictionary returned by run_acceptance_checks().

    Returns
    -------
    str
        A formatted report string.
    """
    lines = []
    lines.append("=" * 70)
    lines.append("               ENGINEERING SURGE ANALYSIS ACCEPTANCE REPORT")
    lines.append("=" * 70)

    status_str = "PASSED" if check_results["passed"] else "FAILED"
    lines.append(f"  Overall Status : {status_str}")
    lines.append(f"  Unit System    : {'SI' if check_results['is_si'] else 'US Customary'}")
    lines.append("-" * 70)

    violations = check_results["violations"]
    if not violations:
        lines.append("  All engineering transient acceptance criteria were MET.")
        lines.append("  No overpressure, subatmospheric, or cavitation violations were detected.")
    else:
        lines.append(f"  Detected {len(violations)} violation(s):")
        lines.append("")
        for v in violations:
            lines.append(f"  * {v['message']}")

    lines.append("=" * 70)
    return "\n".join(lines)
